#!/usr/bin/env bash
alias ll='ls -alFh'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias md='mkdir -p'
alias yarnw="yarn workspace "
alias yarns="yarn start "
alias yarnlp="yarn list --pattern "
alias ff='fzf'
alias vim="nvim"
alias vi="/usr/bin/vim"
alias vimdiff="nvim -d"
alias c="clear && printf '\e[3J'"
alias C=clear
alias t="tmux"
alias ta="t a -t"
alias tls="t ls"
alias tn="t new -s"
alias tks="t kill-session -t"
alias tkss="t kill-server"
alias py='python '
alias pw='prettier --write '
alias ts='$HOME/.tmux/plugins/tmux-resurrect/scripts/save.sh'
alias tr='$HOME/.tmux/plugins/tmux-resurrect/scripts/restore.sh'
alias eshell='exec $SHELL'
alias gst='git st '
alias gcma='git commit --amend '
alias gcmane='git commit --amend --no-edit '
alias gcamupm='git commit -am "updated" && git push github master'
alias hb='sudo systemctl hibernate'
alias rmvimswap='rm ~/.local/share/nvim/swap/*'
