#!/usr/bin/env bash

_archive_projects_f() {
  local _extract_path

  # --------------------------------------------------------------------------
  # PARSE ARGUMENTS
  # --------------------------------------------------------------------------
  local parsed

  if ! parsed="$(
    getopt \
      --longoptions=extract: \
      --options=x: \
      --name "$0" \
      -- "$@"
  )"; then
    return
  fi

  # Provides proper quoting
  eval set -- "$parsed"

  while true; do
    case "$1" in
    --extract | -x)
      _extract_path="$2"
      shift 2
      ;;

    --)
      shift
      break
      ;;

    *)
      Echo "Unknown option ${1}."
      exit 1
      ;;
    esac
  done
  # --------------------------------------------------------------------------
  # END PARSE ARGUMENTS
  # --------------------------------------------------------------------------

  # Remove trailing '/'
  local _output_dir="${ARCHIVE_PROJECT_OUTPUT_DIR%/}"

  if [ -z "${ARCHIVE_PROJECT_OUTPUT_DIR}" ]; then
    echo "You must provide a value for the 'ARCHIVE_PROJECT_OUTPUT_DIR' environment variable"
    return
  fi

  local _absolute_filename="${_output_dir}/proj-archive.tar.gz"

  if [[ -n "${_extract_path}" ]]; then
    local _prefix='Extraction location'

    # Extraction location must be an absolute path
    if [[ ! "${_extract_path}" == /* ]]; then
      echo "${_prefix} '${_extract_path}' is not an absolute path."

      return
    fi

    if echo "${_extract_path}" | grep -q "${_output_dir}"; then
      echo "${_prefix} '${_extract_path}' must not contain '${_output_dir}'."

      return
    fi

    (
      if ! cd "${_extract_path}"; then
        echo "'${_extract_path}' can not be read. Exiting."
        return
      fi

      tar -xzvf "${_absolute_filename}"
    )

    return
  fi

  (
    if ! cd "${HOME}"; then
      echo "'${HOME}' can not be read. Exiting."
      return
    fi

    tar -czvf "${_absolute_filename}" \
      --exclude "**/node_modules/**" \
      --exclude "**/_build/**" \
      --exclude "**/deps/**" \
      --exclude "**/vendor/**" \
      --exclude "**/docker/data/**" \
      --exclude "**/.elixir_ls/**" \
      --exclude "**/.terraform/providers/**" \
      --exclude "**/*cache/**" \
      projects/
  )
}
alias archive-projects='_archive_projects_f'
