#!/usr/bin/env bash
# shellcheck disable=2034,2209,2135,2155,2139,2086,2033
if ! command -v nvim &>/dev/null; then
  return
fi

if [ -n "$_EBNIS_NVIM_BIN" ]; then
  export MYVIMRC="$HOME/dotfiles/.config/nvim/init.lua"

  nvim() {
    "$_EBNIS_NVIM_BIN" -u "$MYVIMRC" "$@"
  }

  export -f nvim

  sv() {
    sudo -E bash -c "$(declare -f nvim); nvim $*"
  }

  export -f sv
else
  alias sv="sudo -E nvim_sudo_e"
fi

export EDITOR="nvim"
# https://bsky.app/profile/bobbby.online/post/3llwpqtwwf22r
# in an iex shell and press ESCAPE+o
export VISUAL="nvim"

# vim
alias vi='/usr/bin/vim'
alias vimdiff="nvim -d"

v() {
  if [ -d "./.venv" ]; then
    _pv -d &>/dev/null
    _pv &>/dev/null

    nvim "$@"
  else
    nvim "$@"
  fi
}
export -f v

alias v.="nvim ."
alias vmin='nvim -u ~/.config/nvim/settings-min.vim'
alias vm='nvim -u ~/.config/nvim/settings-min.vim'
alias vc='nvim --clean'
alias pvv='_pv -d && _pv && nvim'

# set vim theme and background per shell session
# unset
# one theme
alias vt1d='export EBNIS_VIM_THEME=one EBNIS_VIM_THEME_BG=d'
alias vt1l='export EBNIS_VIM_THEME="one" EBNIS_VIM_THEME_BG=l'
# gruvbox8 themes
alias vtg8sd='export EBNIS_VIM_THEME=gruvbox8_soft EBNIS_VIM_THEME_BG=d'
alias vtg8sl='export EBNIS_VIM_THEME=gruvbox8_soft EBNIS_VIM_THEME_BG=l'
alias vtg8hd='export EBNIS_VIM_THEME=gruvbox8_hard EBNIS_VIM_THEME_BG=d'
alias vtg8hl='export EBNIS_VIM_THEME=gruvbox8_hard EBNIS_VIM_THEME_BG=l'
# solarized8 themes
alias vts8d='export EBNIS_VIM_THEME=solarized8 EBNIS_VIM_THEME_BG=d'
alias vts8l='export EBNIS_VIM_THEME=solarized8 EBNIS_VIM_THEME_BG=l'
alias vts8hd='export EBNIS_VIM_THEME=solarized8_high EBNIS_VIM_THEME_BG=d'
alias vts8hl='export EBNIS_VIM_THEME=solarized8_high EBNIS_VIM_THEME_BG=l'

remove_vim_sessionf() {
  local ME
  local filename
  local absolute_path

  ME=$(pwd)
  filename="${ME//\//%}"
  absolute_path="$HOME/.vim/session/$filename.vim"
  rm -rf "$absolute_path"

  remove_vim_undof
}
alias remove_vim_session=remove_vim_sessionf
alias rmvs=remove_vim_sessionf

remove_vim_undof() {
  local ME
  local filename
  local absolute_path
  local prefix

  ME=$(pwd)
  filename="${ME//\//%}%"
  prefix="${HOME}/.vim/undodir"

  # shellcheck disable=2010
  mapfile -t filenames < <(ls -h "${prefix}" | grep -P "${filename}")
  for f in "${filenames[@]}"; do
    absolute_path="${prefix}/${f}"
    rm -rf "${absolute_path}"
  done
}
alias remove_vim_undo='remove_vim_undof'
alias rmvu='remove_vim_undof'

# shellcheck disable=SC2016
# export MANPAGER='nvim -c "%! col -b" -c "set ft=man nomod | let &titlestring=$MAN_PN"'
export MANPAGER='nvim +Man!'
