#!/usr/bin/env bash
# vim ft=bash

_make_sudo_e() {
  local _bin=$1
  local _path
  local _dirname

  if ! _path="$(command -v "$_bin")"; then
    echo "Path for binary $_bin not found. Exiting."
    return 1
  fi

  _dirname="$(dirname "$_path")"

  local _new_bin_name="${_bin}_sudo_e"
  local _copied_bin="$_dirname/$_new_bin_name"

  if ! sudo cp "$_path" "$_copied_bin"; then
    local _local_bin="$HOME/.local/bin"
    _copied_bin="$_local_bin/$_new_bin_name"

    mkdir -p "$_local_bin"
    cp "$_path" "$_copied_bin"
  fi

  if [[ -s "$_copied_bin" ]]; then
    echo "New bin at $_copied_bin."
    return 0
  fi

  echo "Unable to copy binary for \"$_bin\"."
  return 1
}

_make_sudo_e "$@"
