#!/usr/bin/env bash
# shellcheck disable=

if ! command -v tmux &>/dev/null; then
  return
fi

export TP="${TMUX_PANE}"

alias kts='{ ebnis-save-tmux.sh || true; } && tmux kill-server'
alias tks='{ ebnis-save-tmux.sh || true; } && tmux kill-server'
alias ts='ebnis-save-tmux.sh'
alias trs='$HOME/.tmux/plugins/tmux-resurrect/scripts/restore.sh'

export TMUX_PLUGIN_MANAGER_PATH="$HOME/.tmux/plugins/"
tmux_session_wizard="$TMUX_PLUGIN_MANAGER_PATH/tmux-session-wizard/bin"
if [ -d "$tmux_session_wizard" ]; then
  if [ ! -e "$tmux_session_wizard/lst" ]; then
    ln -s "$tmux_session_wizard/t" "$tmux_session_wizard/lst"
  fi
  pathmunge "$tmux_session_wizard"
fi

_c_tmux_script="$(_dot rt)/scripts/c-tmux"
if [[ -e "$_c_tmux_script" ]]; then
  chmod 755 "$_c_tmux_script"

  alias st='c-tmux start_tmux'
  alias lstd='c-tmux list -fx ^dot'
  alias tk='c-tmux kill_tmux'
fi
unset _c_tmux_script
