-- Emmet
Vim.user_emmet_mode = "inv"
Vim.user_emmet_expandabbr_key = ",,"
Vim.user_emmet_expandword_key = "<C-y>;"
Vim.user_emmet_update_tag = "<C-y>u"
Vim.user_emmet_balancetaginward_key = "<C-y>d"
Vim.user_emmet_balancetagoutward_key = "<C-y>D"
Vim.user_emmet_next_key = "<C-y>n"
Vim.user_emmet_prev_key = "<C-y>N"
Vim.user_emmet_imagesize_key = "<C-y>i"
Vim.user_emmet_togglecomment_key = "<C-y>/"
Vim.user_emmet_splitjointag_key = "<C-y>j"
Vim.user_emmet_removetag_key = "<C-y>k"
Vim.user_emmet_anchorizeurl_key = "<C-y>a"
Vim.user_emmet_anchorizesummary_key = "<C-y>A"
Vim.user_emmet_mergelines_key = "<C-y>m"
Vim.user_emmet_codepretty_key = "<C-y>c"
