#!/usr/bin/env bash

___clip_help() {
  read -r -d '' var <<'eof' || true
Copy text to/from remote machine using clipper. Usage:
  clip [OPTIONS]

Options:
  -h
    Print this help text and quit.
  -d
    Get information about actual command that clip will run.

Examples:
  # Get help.
  clip -h

  # Just copy text.
  clip <<<'some text'
  echo 'some text' |clip

  # Get information about actual command that clip will run.
  clip -d

Set up ssh config client:
Host remote_host
  HostName remote_host_ip
  Port 22
  User remote_host_user
  IdentityFile ~/.ssh/identity_file
  StrictHostKeyChecking no
  # The next 2 lines are the most important for the clip executable to work. Clipper must be started on port 8377 on
  # the local machine.
  RemoteForward 8378 localhost:8377
  SetEnv __COPY_PROGRAM__=clip
  ForwardX11 yes # Optional

Set up ssh config server:
In /etc/ssh/sshd_config or /etc/ssh/sshd_config.d/100-macos.conf:
Add/update line:
AcceptEnv LANG LC_* __COPY_PROGRAM__
eof

  echo -e "${var}"
}

nc_flag__=""

if grep -q ubuntu /etc/os-release &>/dev/null; then
  nc_flag__="-N"
fi

clip_nc_cmd__="nc $nc_flag__ localhost 8378"

while getopts 'hd' clip_opts__; do
  case "$clip_opts__" in
  h)
    ___clip_help
    exit
    ;;

  d)
    :
    echo -e "clip command = \n$clip_nc_cmd__"
    exit
    ;;
  *) ;;
  esac
done

eval "$clip_nc_cmd__"
