#!/usr/bin/env bash

main() {
  local _arg=

  if [[ -n "$1" ]]; then
    _arg=$1
  elif [[ ! -t 0 ]]; then
    _arg="$(</dev/stdin)"
  else
    echo "No standard input."
  fi

  if _is_darwin; then
    pbcopy <<<"$_arg"
  elif command -v xclip &>/dev/null; then
    # If we can not copy with xclip (may be because x11 server was not properly setup), then attempt to use clipper.
    if ! xclip -selection c <<<"$_arg" 2>/dev/null; then
      if command -v clip &>/dev/null; then
        clip <<<"$_arg"
      fi
    fi
  elif command -v clip &>/dev/null; then
    clip <<<"$_arg"
  fi
}

main "$@"
