#!/usr/bin/env bash

# https://stackoverflow.com/a/42510314

__drmlogs__() {
  local var_=""
  local is_compose_=""

  while getopts ":ch" var_; do
    case "$var_" in
    h)
      echo "Usage: drmlogs container_name_or_ID [..container_name_or_ID]"
      echo "Usage: drmlogs -c compose_servicename [..compose_servicename]"
      echo "Usage: drmlogs -c"
      exit
      ;;

    c)
      is_compose_=1
      ;;

    *)
      echo "Unknown options \"$OPTARG\""
      exit 1
      ;;
    esac
  done
  shift $((OPTIND - 1))

  local containers_or_services_=("$@")

  if [[ "${#containers_or_services_[@]}" == 0 ]]; then
    if [ -z "$is_compose_" ]; then
      echo "You must provide container name(s)"
      exit 1
    fi

    mapfile -t containers_or_services_ < <(
      docker compose ps --all --format "{{.Service}}"
    )
  fi

  for item_ in "${containers_or_services_[@]}"; do
    local container_=""

    if [ -n "$is_compose_" ]; then
      container_="$(docker compose ps --quiet --all "$item_")"
    else
      container_="$item_"
    fi

    log_path_=$(
      docker inspect --format='{{.LogPath}}' "$container_"
    )

    echo "" | sudo tee "$log_path_"
    echo -e "truncated:\n$item_\n$container_\n$log_path_"
  done
}

__drmlogs__ "$@"
