#!/usr/bin/env bash

# https://stackoverflow.com/a/42510314

__drmlogs__() {
  local var_=""
  local is_compose_=""

  while getopts ":ch" var_; do
    case "$var_" in
    h)
      echo "Usage: drmlogs container_name_or_ID [..container_name_or_ID]"
      echo "Usage: drmlogs -c compose_servicename [..compose_servicename]"
      exit
      ;;

    c)
      is_compose_=1
      ;;

    *)
      echo "Unknown options \"$OPTARG\""
      exit 1
      ;;
    esac
  done
  shift $((OPTIND - 1))

  for container_ in "$@"; do
    if [ -n "$is_compose_" ]; then
      container_="$(docker compose ps --quiet "$container_")"
    fi

    log_path_=$(docker inspect --format='{{.LogPath}}' "$container_")

    echo "" | sudo tee "$log_path_"
    echo -e "truncated\n$log_path_"
  done
}

__drmlogs__ "$@"
