#!/usr/bin/env bash
# shellcheck disable=

__external--install-yazi() {
  : "Install superfile - a pretty fancy and modern terminal file manager"

  _echo "INSTALLING SUPERFILE"

  # fzf

  install-ripgrep

  if _is_darwin; then
    brew update

    brew install \
      yazi \
      ffmpeg \
      sevenzip \
      poppler \
      fd \
      zoxide \
      resvg \
      imagemagick \
      font-symbols-only-nerd-font
  else
    sudo apt install -y \
      ffmpeg \
      7zip \
      poppler-utils \
      fd-find \
      ripgrep \
      zoxide \
      imagemagick

    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    rustup update
    cargo install --force yazi-build

    local config_dir_=""
    config_dir_="$(_dot rt)/.config/yazi"
    if [ -d "$config_dir_" ]; then
      rm -rf "$HOME/.config/yazi"
      ln -s "$config_dir_" "$HOME/.config"
    fi
  fi

  _echo "Superfile installed successfully"
}

__external--install-yazi "$@"
