#!/usr/bin/env bash
# shellcheck disable=

width_=${2:-90%}
height_=${2:-90%}

tmux_session="${DEFAULT_TMUX_SESSION:-dot}"
if [ "$(tmux display-message -p -F "#{session_name}")" = "$tmux_session" ]; then
  tmux detach-client
else
  tmux popup \
    -d "$HOME/dotfiles" \
    -w "$width_" \
    -h "$height_" \
    -e TMUX_POPUP_SESSION=dot \
    -E \
    "tmux attach -t $tmux_session || tmux new -s $tmux_session"
fi
