#!/usr/bin/env bash
# shellcheck disable=

remove_debug_logs_in_dir() {
  local dir_="$1"

  local cmd_="find $dir_ -type f -print0"
  cmd_+=" | xargs -0"
  cmd_+=" sed -i"
  cmd_+=" '/# NOTE: --START-- DEBUG LOG {/,/# NOTE: --END-- DEBUG LOG }/d'"

  bash -c "$cmd_"
}

remove_debug_logs_in_dir "$@"
