#!/usr/bin/env bash
# shellcheck disable=2034,2209,2135,2155,2046

if [[ "$1" =~ ^/ ]]; then
  env_file_abs_path="$1"
else
  env_file_abs_dir="$(
    (cd -- "$(dirname "$1")" || exit) >/dev/null 2>&1
    pwd -P
  )"

  env_file_abs_path="$env_file_abs_dir/$1"
fi

new_asbolute_file_path="${env_file_abs_path}.n"
rm -rf "${new_asbolute_file_path}"

declare -A env_key_to_value_map

line_regex="^[^#]+.+"

# shellcheck disable=2013
while read -r line; do
  if [[ "$line" =~ $line_regex ]]; then
    key=$(echo "$line" | cut -d '=' -f 1)
    val=$(echo "$line" | cut -d'=' -f 2-)

    for line_with_varirables in $(echo "$val" | grep -Po '\$\{\K.+?(?=\})'); do
      variable_text="\${$line_with_varirables}"
      variable_val="${env_key_to_value_map[$line_with_varirables]}"

      if [[ -z "$variable_val" ]]; then
        variable_val=${!line_with_varirables}
      fi

      val="${val//$variable_text/$variable_val}"
    done

    env_key_to_value_map["$key"]="${val}"
  fi
done <<<$(cat "$env_file_abs_path")

env_key_to_value_map["DOCKER_ENV_FILE"]="${new_asbolute_file_path}"

is_file=1
text=

if [[ -n "$2" ]]; then
  is_file=
  text=""
fi

for key in "${!env_key_to_value_map[@]}"; do
  out="$key=${env_key_to_value_map[$key]}"

  if [[ "$is_file" ]]; then
    echo "$out" >>"$new_asbolute_file_path"
  else
    text="$out $text"
  fi
done

if [[ "$is_file" ]]; then
  sort "$new_asbolute_file_path" -o "$new_asbolute_file_path"
else
  echo "$text"
fi
