-- Emmet
vim.user_emmet_mode = "inv"
vim.user_emmet_expandabbr_key = ",,"
vim.user_emmet_expandword_key = "<C-y>;"
vim.user_emmet_update_tag = "<C-y>u"
vim.user_emmet_balancetaginward_key = "<C-y>d"
vim.user_emmet_balancetagoutward_key = "<C-y>D"
vim.user_emmet_next_key = "<C-y>n"
vim.user_emmet_prev_key = "<C-y>N"
vim.user_emmet_imagesize_key = "<C-y>i"
vim.user_emmet_togglecomment_key = "<C-y>/"
vim.user_emmet_splitjointag_key = "<C-y>j"
vim.user_emmet_removetag_key = "<C-y>k"
vim.user_emmet_anchorizeurl_key = "<C-y>a"
vim.user_emmet_anchorizesummary_key = "<C-y>A"
vim.user_emmet_mergelines_key = "<C-y>m"
vim.user_emmet_codepretty_key = "<C-y>c"
